name: Deploy Django App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "task-manager-api-f"
          heroku_email: ${{ secrets.EMAIL }}
          procfile: "web: uvicorn main:app"
          appdir: "backend"
          healthcheck: "https://task-manager-api-f.herokuapp.com/api/user/healthy/"